send-information-to-actionbar: true
send-message-when-level-up: true
levelup-message-type: title # available types; title, actionbar, normal-message, bossbar
stock-kill-count: true # this will be stocked on "playerdata/uuid of player.yml"
language-file: en_US

monster-xps:
    zombie: 8
    creeper: 12
    skeleton: 10
    blaze: 16
    cave spider: 14
    drowned: 20
    elder guardian: 25
    enderman: 30
    ghast: 24
    normal guardian: 15
    hoglin: 20
    husk: 15
    magma cube: 5
    phantom: 20
    piglin brute: 15
    piglin: 10
    pillager: 20
    spider: 10
    slime: 5
    stray: 25
    vex: 40
    witch: 20
    wither skeleton: 30
    zoglin: 30
    zombie pigman: 20


skills:
    Strength:
        max-level: 20
        each-xp-per-level: 250
        each-damage-buff-per-level: 1
    Intelligence:
        max-level: 20
        each-xp-per-level: 250
    XP-gain:
        max-level: 20
        each-xp-per-level: 250
        each-xp-bonus-per-level: 5
    Health:
        max-level: 20
        each-xp-per-level: 250
        each-health-per-level: 1
